// 种子数据, 由 data/app.json 同步生成

const fences = [
  {
    "name": "景洪橄榄坝水泥卸货点",
    "code": "F-0000001",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "一车队（云南钦圣）",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.936254",
    "lat": "21.860692",
    "location": "云南省西双版纳傣族自治州景洪市勐罕镇老帅钢筋厂",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-21 17:34:39",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景东钢筋下货点",
    "code": "F-0000002",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "101.120965",
    "lat": "24.245489",
    "location": "云南省普洱市景东彝族自治县花山镇083乡道",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "景东彝族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 11:10:30",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "磨憨红砖厂装货点",
    "code": "F-0000003",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "101.726828",
    "lat": "21.211167",
    "location": "磨憨经济开发区页岩砖厂",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "勐腊县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 11:10:25",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 3,
    "unloadTime": 0,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪红砖卸货点",
    "code": "F-0000004",
    "type": "点",
    "cat": "门店",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.82049",
    "lat": "21.977582",
    "location": "云南省西双版纳傣族自治州景洪市曼弄枫街道榕林时光二期",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 11:10:20",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 3,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪白土装货地",
    "code": "F-0000005",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 1000,
    "lng": "100.511953",
    "lat": "21.488735",
    "location": "云南省西双版纳傣族自治州景洪市勐龙镇景洪勐宋云巅茶叶专业合作社",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 11:10:10",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 3,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "易门白土卸货地",
    "code": "F-0000006",
    "type": "点",
    "cat": "门店",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈终点",
    "radius": 1000,
    "lng": "102.192749",
    "lat": "24.719523",
    "location": "云南省玉溪市易门县龙泉街道云南远方陶瓷有限公司",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "易门县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 11:10:02",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 3,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "玉昆卸货点",
    "code": "F-0000007",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈终点",
    "radius": 2000,
    "lng": "102.172318",
    "lat": "24.066141",
    "location": "云南省玉溪市峨山彝族自治县化念镇山松迭",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "峨山彝族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 11:09:56",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 3,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "龙鑫铁精粉景洪装货地",
    "code": "F-0000008",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.643978",
    "lat": "21.506257",
    "location": "云南省西双版纳傣族自治州景洪市勐龙镇041乡道",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 11:09:33",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 3,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "西双版纳鑫禾商贸（小红砖卸货点）",
    "code": "F-0000009",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "101.301883",
    "lat": "21.322227",
    "location": "云南省西双版纳傣族自治州勐腊县勐满镇171县道勐腊县鑫合商贸有限公司",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "勐腊县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 09:50:52",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪关坪吉利砖厂（水泥卸货点）",
    "code": "F-0000010",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.885074",
    "lat": "22.322868",
    "location": "云南省西双版纳傣族自治州景洪市大渡岗乡景讷公路",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 09:32:41",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "普洱建峰水泥厂装货点",
    "code": "F-0000011",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.879013",
    "lat": "22.775742",
    "location": "云南省普洱市思茅区南屏镇云南普洱西南水泥有限公司",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "思茅区",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-14 09:30:25",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "大勐龙金点糖业有限公司东北（铁矿装货地）",
    "code": "F-0000012",
    "type": "点",
    "cat": "仓库",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.66845",
    "lat": "21.535852",
    "location": "云南省西双版纳傣族自治州景洪市勐龙镇3号路",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "曹涛",
    "modifyTime": "2026-07-12 09:54:14",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪勐龙镇（锰矿装货点）",
    "code": "F-0000013",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.671582",
    "lat": "21.537659",
    "location": "云南省西双版纳傣族自治州景洪市勐龙镇175县道中国石油加油站",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-06 11:43:02",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪橄榄坝钢筋卸货点",
    "code": "F-0000014",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.944284",
    "lat": "21.851076",
    "location": "云南省西双版纳傣族自治州景洪市勐罕镇孔雀园西双版纳傣族园",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-04 17:54:49",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "澜沧钢筋卸货点",
    "code": "F-0000015",
    "type": "面",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 0,
    "lng": "99.930136",
    "lat": "22.575512",
    "location": "云南省普洱市澜沧拉祜族自治县勐朗镇明雅鱼庄",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "澜沧拉祜族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-04 17:54:41",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "元江干坝片区（锰矿卸货点）",
    "code": "F-0000016",
    "type": "点",
    "cat": "物流园",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈终点",
    "radius": 2000,
    "lng": "101.962965",
    "lat": "23.684421",
    "location": "云南省玉溪市元江哈尼族彝族傣族自治县甘庄街道云南果研社农业科技发展有限公司",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "元江哈尼族彝族傣族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-04 10:14:02",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "尖峰水泥厂（卸货地）",
    "code": "F-0000017",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.734753",
    "lat": "22.632305",
    "location": "云南省普洱市思茅区六顺镇云南尖峰水泥有限公司(东1门)",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "思茅区",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-07-02 09:43:04",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "普洱南屏镇化肥卸货点",
    "code": "F-0000018",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.862068",
    "lat": "22.765608",
    "location": "云南省普洱市思茅区南屏镇思茅区南屏镇整碗村民委员会",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "思茅区",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-07-01 10:29:58",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "杨武铁精粉下货点",
    "code": "F-0000019",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈终点",
    "radius": 2000,
    "lng": "102.141936",
    "lat": "23.907884",
    "location": "云南省玉溪市新平彝族傣族自治县扬武镇213国道",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "新平彝族傣族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-06-30 09:12:40",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "普洱景谷红狮水泥有限公司",
    "code": "F-0000020",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.896103",
    "lat": "22.089414",
    "location": "云南省西双版纳傣族自治州景洪市勐养镇景洪市司法局勐养司法所景洪金象商务酒店",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "曹涛",
    "modifyTime": "2026-06-27 17:33:36",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 3,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "研和化肥厂",
    "code": "F-0000021",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈起点",
    "radius": 2000,
    "lng": "102.521667",
    "lat": "24.224273",
    "location": "云南省玉溪市红塔区研和街道云南省玉溪化肥厂有限责任公司",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "红塔区",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-24 21:24:17",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景谷凤山镇",
    "code": "F-0000022",
    "type": "点",
    "cat": "其他",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.794384",
    "lat": "23.677374",
    "location": "云南省普洱市景谷傣族彝族自治县凤山镇凤山镇人民政府",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "景谷傣族彝族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-24 21:22:18",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "版纳磨憨镇",
    "code": "F-0000023",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "101.563342",
    "lat": "21.461995",
    "location": "云南省西双版纳傣族自治州勐腊县勐腊镇勐腊县勐腊县人民政府",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "勐腊县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-24 21:00:33",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "孟连县",
    "code": "F-0000024",
    "type": "面",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 0,
    "lng": "99.577431",
    "lat": "22.328244",
    "location": "云南省普洱市孟连傣族拉祜族佤族自治县娜允镇阿良泰味小吃",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "孟连傣族拉祜族佤族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-24 20:52:09",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景谷永平镇（钢筋卸货点）",
    "code": "F-0000025",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.396239",
    "lat": "23.416358",
    "location": "云南省普洱市景谷傣族彝族自治县永平镇永平镇人民政府",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "景谷傣族彝族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-24 20:45:10",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "勐养镇（卸货地）",
    "code": "F-0000026",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.798473",
    "lat": "22.014657",
    "location": "云南省西双版纳傣族自治州景洪市允景洪街道景洪市景洪市机关办公大楼",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-22 11:51:24",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 1,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "普洱景谷县城",
    "code": "F-0000027",
    "type": "面",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 200,
    "lng": "100.704015",
    "lat": "23.505148",
    "location": "云南省普洱市景谷傣族彝族自治县威远镇文明路134号",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "景谷傣族彝族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-18 19:35:31",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪勐旺乡",
    "code": "F-0000028",
    "type": "面",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 200,
    "lng": "101.297198",
    "lat": "22.491468",
    "location": "云南省西双版纳傣族自治州景洪市勐旺乡049乡道",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-18 19:28:31",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "镇沅振太乡",
    "code": "F-0000029",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "101.107142",
    "lat": "24.007081",
    "location": "云南省普洱市镇沅彝族哈尼族拉祜族自治县恩乐镇镇沅彝族哈尼族拉祜族自治县镇沅彝族哈尼族拉祜族自治县人民政府",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "镇沅彝族哈尼族拉祜族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-17 08:54:43",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "勐海县",
    "code": "F-0000030",
    "type": "面",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 200,
    "lng": "100.439407",
    "lat": "21.972396",
    "location": "云南省西双版纳傣族自治州勐海县勐海镇沙河小镇水街二期",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "勐海县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-14 10:09:00",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 3,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "普洱市区钢铁卸货网点",
    "code": "F-0000031",
    "type": "面",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 0,
    "lng": "100.957713",
    "lat": "22.786961",
    "location": "云南省普洱市思茅区南屏镇156县道",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "思茅区",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-14 10:08:10",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "宁洱镇",
    "code": "F-0000032",
    "type": "面",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 200,
    "lng": "101.036847",
    "lat": "23.063173",
    "location": "云南省普洱市宁洱哈尼族彝族自治县宁洱镇天壁路",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "宁洱哈尼族彝族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-14 10:07:29",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "峨山鑫钰公司货场",
    "code": "F-0000033",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈终点",
    "radius": 2000,
    "lng": "102.344391",
    "lat": "24.212087",
    "location": "云南省玉溪市峨山彝族自治县双江街道峨山鑫钰公司货场",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "峨山彝族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-13 13:05:33",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "尖峰水泥场（装货地）",
    "code": "F-0000034",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.73557",
    "lat": "22.632028",
    "location": "云南省普洱市思茅区六顺镇云南尖峰水泥有限公司(东1门)",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "思茅区",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "陈海波管理员",
    "modifyTime": "2026-06-12 16:07:13",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "普洱墨江通关（钢筋卸货地）",
    "code": "F-0000035",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "101.691018",
    "lat": "23.434638",
    "location": "云南省普洱市墨江哈尼族自治县联珠镇墨江哈尼族自治县墨江哈尼族自治县人民政府",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "墨江哈尼族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-11 13:45:52",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "安宁昆钢",
    "code": "F-0000036",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈起点",
    "radius": 2000,
    "lng": "102.368429",
    "lat": "24.943507",
    "location": "云南省昆明市安宁市草铺街道昆畹西路8号云南嘉浩志达混凝土有限公司",
    "prov": "云南省",
    "city": "昆明市",
    "dist": "安宁市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-11 09:43:27",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪神石山（水泥卸货）",
    "code": "F-0000037",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.685949",
    "lat": "22.056728",
    "location": "云南省西双版纳傣族自治州景洪市嘎栋街道神石山",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-11 09:12:23",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "玉溪水电志达混凝土有限公司",
    "code": "F-0000038",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈起点",
    "radius": 2000,
    "lng": "102.534755",
    "lat": "24.436947",
    "location": "云南省玉溪市红塔区北城街道玉溪水电志达混凝土有限责任公司",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "红塔区",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "管理员",
    "modifyTime": "2026-06-09 14:15:17",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪钢铁下货网点",
    "code": "F-0000039",
    "type": "面",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 0,
    "lng": "100.775627",
    "lat": "21.986226",
    "location": "云南省西双版纳傣族自治州景洪市允景洪街道观澜路",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "管理员",
    "modifyTime": "2026-06-08 14:20:19",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "大勐龙景洪赢海通经贸有限公司(原矿装货地)",
    "code": "F-0000040",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.683575",
    "lat": "21.555815",
    "location": "云南省西双版纳傣族自治州景洪市勐龙镇175县道",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-07 11:06:41",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "峨山贵州佳俊矿业",
    "code": "F-0000041",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈终点",
    "radius": 2000,
    "lng": "102.387985",
    "lat": "24.190656",
    "location": "云南省玉溪市峨山彝族自治县双江街道峨山站",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "峨山彝族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-07 10:57:56",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "勐遮（水泥卸货地）",
    "code": "F-0000042",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.451271",
    "lat": "21.95999",
    "location": "云南省西双版纳傣族自治州勐海县勐海镇勐海县勐海县人民政府",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "勐海县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-06 14:38:31",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "大勐龙水泥卸货地",
    "code": "F-0000043",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.678927",
    "lat": "21.582564",
    "location": "云南省西双版纳傣族自治州景洪市勐龙镇勐龙边境派出所",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-06 14:34:57",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "澜沧三环水泥公司（水渣卸货、水泥装货点）",
    "code": "F-0000044",
    "type": "点",
    "cat": "工厂",
    "ioType": "收/发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "99.976648",
    "lat": "22.516791",
    "location": "云南省普洱市澜沧拉祜族自治县勐朗镇澜沧三环水泥有限公司",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "澜沧拉祜族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-06 14:29:39",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "普洱景谷永平镇（化肥卸货地）",
    "code": "F-0000045",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.39507",
    "lat": "23.419855",
    "location": "云南省普洱市景谷傣族彝族自治县永平镇景谷吉泰医院",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "景谷傣族彝族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-06 14:19:52",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "普洱市宁洱天恒水泥有限公司",
    "code": "F-0000046",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "101.074497",
    "lat": "23.025361",
    "location": "云南省普洱市宁洱哈尼族彝族自治县宁洱镇云南普洱天恒水泥有限责任公司",
    "prov": "云南省",
    "city": "普洱市",
    "dist": "宁洱哈尼族彝族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-05 14:58:24",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪东风镇（水泥卸货地）",
    "code": "F-0000047",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.744336",
    "lat": "21.702555",
    "location": "云南省西双版纳傣族自治州景洪市勐龙镇允大公路249号",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-05 14:32:12",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "玉溪仙福钢铁(集团)有限公司",
    "code": "F-0000048",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈起点",
    "radius": 2000,
    "lng": "102.185022",
    "lat": "24.014056",
    "location": "云南省玉溪市新平彝族傣族自治县扬武镇仙福钢铁(集团)有限公司高线厂(建设中)",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "新平彝族傣族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-05 13:43:20",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "玉溪研和工业园区",
    "code": "F-0000049",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "102.495917",
    "lat": "24.249876",
    "location": "云南省玉溪市红塔区研和街道研和工业园区太标集团",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "红塔区",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李宏俊",
    "modifyTime": "2026-06-05 11:44:15",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "版纳景洪沙河社区红狮水泥卸货地",
    "code": "F-0000050",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.738208",
    "lat": "22.008082",
    "location": "云南省西双版纳傣族自治州景洪市嘎栋街道红狮水泥鼎茂商砼",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-05 11:38:34",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "大勐龙铁精粉装货地（玉丰进出口贸易）",
    "code": "F-0000051",
    "type": "点",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "100.68093",
    "lat": "21.553124",
    "location": "云南省西双版纳傣族自治州景洪市勐龙镇勐龙鑫龙汽车修理",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-05 11:29:21",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "化念铁精粉卸货地",
    "code": "F-0000052",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈终点",
    "radius": 2000,
    "lng": "102.205439",
    "lat": "24.050683",
    "location": "云南省玉溪市峨山彝族自治县化念镇213国道",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "峨山彝族自治县",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-05 11:20:30",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 2,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "大开门水渣装货地",
    "code": "F-0000053",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "圈起点",
    "radius": 2000,
    "lng": "102.170168",
    "lat": "24.015362",
    "location": "永发水泥厂西南侧190米新平甬福环保有限责任公司",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "新平彝族傣族自治县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "钱育升",
    "modifyTime": "2026-06-04 13:40:52",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "景洪水泥卸货网点",
    "code": "F-0000054",
    "type": "面",
    "cat": "仓库",
    "ioType": "收货区域",
    "dept": "云南钦圣新能源科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 0,
    "lng": "100.882286",
    "lat": "21.978872",
    "location": "云南省西双版纳傣族自治州景洪市江北街道",
    "prov": "云南省",
    "city": "西双版纳傣族自治州",
    "dist": "景洪市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-06-03 15:10:01",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 4,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "内蒙古王远实业有限公司",
    "code": "F-0000055",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "112.99463",
    "lat": "40.38915",
    "location": "内蒙古自治区乌兰察布市丰镇市巨宝庄镇内蒙古王远实业有限公司",
    "prov": "内蒙古自治区",
    "city": "乌兰察布市",
    "dist": "丰镇市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-05-25 16:57:37",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "玉溪化肥厂",
    "code": "F-0000056",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "云南宁核聚力供应链有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "102.521667",
    "lat": "24.224273",
    "location": "云南省玉溪市红塔区研和街道云南昆钢制管有限公司",
    "prov": "云南省",
    "city": "玉溪市",
    "dist": "红塔区",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "宁核聚力管理员",
    "modifyTime": "2026-05-23 14:31:18",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 1.67,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "山西禹王煤炭气化有限公司",
    "code": "F-0000057",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 1500,
    "lng": "112.714202",
    "lat": "38.346353",
    "location": "山西省忻州市忻府区兰村乡山西禹王煤炭气化有限公司(西北门)",
    "prov": "山西省",
    "city": "忻州市",
    "dist": "忻府区",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-05-12 09:30:44",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "山西诺兰德再生资源",
    "code": "F-0000058",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "运营部（沃远智行）",
    "share": "部门",
    "role": "不参与环线",
    "radius": 200,
    "lng": "112.76285",
    "lat": "38.779238",
    "location": "山西省忻州市原平市吉祥街道山西诺兰德再生资源开发有限公司",
    "prov": "山西省",
    "city": "忻州市",
    "dist": "原平市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "欧福伟",
    "modifyTime": "2026-05-01 13:11:52",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 1.67,
    "unloadTime": 0,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "天津",
    "code": "F-0000059",
    "type": "点",
    "cat": "码头堆场",
    "ioType": "收货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "117.729502",
    "lat": "38.990806",
    "location": "天津市滨海新区新港街道港一一纬路",
    "prov": "天津市",
    "city": "天津市",
    "dist": "天津市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "管理员",
    "modifyTime": "2026-04-23 17:33:21",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 3,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "天津港第四港埠有限公司",
    "code": "F-0000060",
    "type": "点",
    "cat": "码头堆场",
    "ioType": "发货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "117.7541",
    "lat": "38.988829",
    "location": "天津市滨海新区新港街道天津港第四港埠有限公司天津港二四办公大楼",
    "prov": "天津市",
    "city": "天津市",
    "dist": "天津市",
    "remark": "",
    "openStatus": "未开通",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-23 09:14:22",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "无空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "新石煤焦化有限公司",
    "code": "F-0000061",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "112.688478",
    "lat": "38.948706",
    "location": "山西省忻州市原平市崞阳镇跨越大道",
    "prov": "山西省",
    "city": "忻州市",
    "dist": "原平市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-18 10:10:19",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "五台县大建安鼎鑫石料加工厂",
    "code": "F-0000062",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "113.110397",
    "lat": "38.618833",
    "location": "山西省忻州市五台县建安镇五台县大建安鼎鑫石料加工厂",
    "prov": "山西省",
    "city": "忻州市",
    "dist": "五台县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-18 10:10:13",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "恒晟镁业公司",
    "code": "F-0000063",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "113.122449",
    "lat": "40.164883",
    "location": "山西省大同市新荣区西村乡恒晟镁业公司",
    "prov": "山西省",
    "city": "大同市",
    "dist": "新荣区",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-18 10:10:07",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 3,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "鑫宇煤炭气化有限公司",
    "code": "F-0000064",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "111.513226",
    "lat": "38.692281",
    "location": "山西省忻州市岢岚县岚漪镇鑫宇煤炭气化有限公司",
    "prov": "山西省",
    "city": "忻州市",
    "dist": "岢岚县",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-18 10:09:58",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 2,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "同盛二期",
    "code": "F-0000065",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "113.18459",
    "lat": "40.413805",
    "location": "内蒙古自治区乌兰察布市丰镇市南城区街道同盛二期",
    "prov": "内蒙古自治区",
    "city": "乌兰察布市",
    "dist": "丰镇市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-18 10:09:49",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 3,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "太原钢铁集团有限公司",
    "code": "F-0000066",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "112.530489",
    "lat": "37.939609",
    "location": "山西省太原市尖草坪区尖草坪街道太原钢铁集团有限公司",
    "prov": "山西省",
    "city": "太原市",
    "dist": "尖草坪区",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-18 10:09:35",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 8,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "山西同德兴华特钢有限公司",
    "code": "F-0000067",
    "type": "点",
    "cat": "工厂",
    "ioType": "收货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "113.307188",
    "lat": "40.181023",
    "location": "山西省大同市新荣区古店镇山西同德兴华特钢有限公司",
    "prov": "山西省",
    "city": "大同市",
    "dist": "新荣区",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-18 10:09:11",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 0,
    "unloadTime": 1.33,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  },
  {
    "name": "丰镇市同盛合金有限公司",
    "code": "F-0000068",
    "type": "点",
    "cat": "工厂",
    "ioType": "发货区域",
    "dept": "内蒙古沃远智行物流科技有限公司",
    "share": "部门",
    "role": "不参与环线",
    "radius": 2000,
    "lng": "113.184914",
    "lat": "40.410694",
    "location": "内蒙古自治区乌兰察布市丰镇市南城区街道丰镇市同盛合金有限公司",
    "prov": "内蒙古自治区",
    "city": "乌兰察布市",
    "dist": "丰镇市",
    "remark": "",
    "openStatus": "",
    "account": "",
    "modifier": "李少男",
    "modifyTime": "2026-04-18 10:09:04",
    "enableStatus": "启用",
    "settleBody": "",
    "loadTime": 3,
    "unloadTime": 0,
    "emptyType": "装货空驶",
    "allowance": 0,
    "highway": ""
  }
];


const circleRows = [
  [
    "QXC-20260720-0001",
    "云A·K12345",
    "张建国",
    "安宁昆钢",
    "峨山鑫钰公司货场",
    "s",
    "2026-07-15 06:30",
    "2026-07-18 18:45",
    "3d 12h15m",
    3,
    2,
    4.7,
    0.8,
    3,
    "285.6",
    "自动结束"
  ],
  [
    "QXC-20260720-0002",
    "云A·K67890",
    "李伟",
    "玉溪仙福钢铁(集团)有限公司",
    "化念铁精粉卸货地",
    "s",
    "2026-07-15 07:10",
    "2026-07-18 16:30",
    "3d 9h20m",
    1.6,
    1.4,
    4.7,
    0.5,
    2,
    "198.3",
    "自动结束"
  ],
  [
    "QXC-20260720-0003",
    "云A·K12345",
    "张建国",
    "研和化肥厂",
    "玉昆卸货点",
    "p",
    "2026-07-15 13:20",
    "—",
    "—",
    "—",
    "—",
    "—",
    "—",
    1,
    "85.2",
    "—"
  ],
  [
    "QXC-20260720-0004",
    "云A·K90123",
    "王强",
    "大开门水渣装货地",
    "玉昆卸货点",
    "s",
    "2026-07-15 08:00",
    "2026-07-18 14:30",
    "3d 6h30m",
    1,
    0.8,
    4.8,
    0.4,
    1,
    "156.8",
    "自动结束"
  ],
  [
    "QXC-20260720-0005",
    "云A·K34567",
    "赵明",
    "安宁昆钢",
    "化念铁精粉卸货地",
    "w",
    "2026-07-15 09:30",
    "2026-07-18 23:45",
    "3d 14h15m",
    3.5,
    3,
    5.3,
    1,
    4,
    "342.1",
    "手动结束"
  ],
  [
    "QXC-20260720-0006",
    "云A·K67890",
    "李伟",
    "玉溪水电志达混凝土有限公司",
    "元江干坝片区（锰矿卸货点）",
    "s",
    "2026-07-15 14:00",
    "2026-07-19 02:30",
    "3d 12h30m",
    2.5,
    2.3,
    4.9,
    0.7,
    3,
    "312.5",
    "自动结束"
  ],
  [
    "QXC-20260720-0007",
    "云A·K12345",
    "张建国",
    "安宁昆钢",
    "易门白土卸货地",
    "p",
    "2026-07-16 06:30",
    "—",
    "—",
    "—",
    "—",
    "—",
    "—",
    2,
    "145.6",
    "—"
  ],
  [
    "QXC-20260720-0008",
    "云A·K34567",
    "赵明",
    "玉溪仙福钢铁(集团)有限公司",
    "峨山贵州佳俊矿业",
    "qp",
    "2026-07-15 14:30",
    "2026-07-19 00:50",
    "3d 10h20m",
    2.8,
    1.8,
    4.2,
    0.6,
    3,
    "268.4",
    "自动结束"
  ],
  [
    "QXC-20260720-0009",
    "云A·K90123",
    "王强",
    "研和化肥厂",
    "杨武铁精粉下货点",
    "s",
    "2026-07-15 15:00",
    "2026-07-19 04:25",
    "3d 13h25m",
    3.3,
    2.3,
    5.3,
    0.9,
    3,
    "298.7",
    "自动结束"
  ],
  [
    "QXC-20260720-0010",
    "云A·K34567",
    "赵明",
    "大开门水渣装货地",
    "峨山鑫钰公司货场",
    "p",
    "2026-07-16 07:00",
    "—",
    "—",
    "—",
    "—",
    "—",
    "—",
    2,
    "225.3",
    "—"
  ],
  [
    "QXC-20260720-0011",
    "云A·K67890",
    "李伟",
    "玉溪仙福钢铁(集团)有限公司",
    "化念铁精粉卸货地",
    "p",
    "2026-07-17 08:15",
    "—",
    "—",
    "—",
    "—",
    "—",
    "—",
    2,
    "168.4",
    "—"
  ],
  [
    "QXC-20260720-0012",
    "云A·K90123",
    "王强",
    "大开门水渣装货地",
    "玉昆卸货点",
    "p",
    "2026-07-17 09:40",
    "—",
    "—",
    "—",
    "—",
    "—",
    "—",
    3,
    "254.1",
    "—"
  ]
];

const trips = [
  {
    "code": "QXC-20260720-0001",
    "vehicle": "K12345",
    "driver": "张建国",
    "status": "s",
    "endType": "自动结束",
    "startPool": "安宁昆钢",
    "startActual": "安宁昆钢",
    "endPool": "峨山鑫钰公司货场",
    "endActual": "峨山鑫钰公司货场",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-15 06:30",
    "endTime": "2026-07-15 18:45",
    "totalDuration": "12h 15min",
    "totalDurationH": "12.3小时",
    "mileage": "285.6",
    "createTime": "2026-07-15 18:45:03",
    "lastCalcTime": "2026-07-15 18:45:03",
    "timeAnalysis": {
      "loading": {
        "h": 3,
        "pct": 28.8
      },
      "driving": {
        "h": 4.7,
        "pct": 44.8
      },
      "unloading": {
        "h": 2,
        "pct": 19.2
      },
      "charging": {
        "h": 0.8,
        "pct": 7.2
      },
      "total": 10.4
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "安宁昆钢",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "安宁昆钢 → 景洪白土装货地",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "景洪白土装货地 → 景洪橄榄坝钢筋卸货点",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "景洪橄榄坝钢筋卸货点 → 峨山鑫钰公司货场",
        "time": "—"
      }
    ],
    "chargingSessions": [
      {
        "taskId": "Y2026072200010001",
        "enteredFenceAt": "2026-07-15 10:10",
        "chargeStartedAt": "2026-07-15 10:18"
      },
      {
        "taskId": "Y2026072200010002",
        "enteredFenceAt": "2026-07-15 13:42",
        "chargeStartedAt": "2026-07-15 14:00"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "安宁昆钢 → 景洪白土装货地",
        "goods": "钢材",
        "from": "安宁昆钢",
        "to": "景洪白土装货地",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "开始任务",
        "fare": 900,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200010001"
      },
      {
        "seq": 2,
        "route": "景洪白土装货地 → 景洪橄榄坝钢筋卸货点",
        "goods": "中转",
        "from": "景洪白土装货地",
        "to": "景洪橄榄坝钢筋卸货点",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "中间任务",
        "fare": 1037,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200010002"
      },
      {
        "seq": 3,
        "route": "景洪橄榄坝钢筋卸货点 → 峨山鑫钰公司货场",
        "goods": "水泥",
        "from": "景洪橄榄坝钢筋卸货点",
        "to": "峨山鑫钰公司货场",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "结束任务",
        "fare": 1173,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200010003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0002",
    "vehicle": "K12346",
    "driver": "李伟",
    "status": "s",
    "endType": "自动结束",
    "startPool": "玉溪仙福钢铁(集团)有限公司",
    "startActual": "玉溪仙福钢铁(集团)有限公司",
    "endPool": "化念铁精粉卸货地",
    "endActual": "化念铁精粉卸货地",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-15 07:10",
    "endTime": "2026-07-19 16:20",
    "totalDuration": "3d 9h20m",
    "totalDurationH": "3d 9h20m",
    "mileage": "198.3",
    "createTime": "2026-07-19 16:20:03",
    "lastCalcTime": "2026-07-19 16:20:03",
    "timeAnalysis": {
      "loading": {
        "h": 1.6,
        "pct": 19.5
      },
      "driving": {
        "h": 4.7,
        "pct": 57.3
      },
      "unloading": {
        "h": 1.4,
        "pct": 17.1
      },
      "charging": {
        "h": 0.5,
        "pct": 6.1
      },
      "total": 8.2
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "玉溪仙福钢铁(集团)有限公司",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "玉溪仙福钢铁(集团)有限公司 → 玉溪研和工业园区",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "玉溪研和工业园区 → 玉溪化肥厂",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "玉溪化肥厂 → 化念铁精粉卸货地",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "玉溪仙福钢铁(集团)有限公司 → 玉溪研和工业园区",
        "goods": "钢材",
        "from": "玉溪仙福钢铁(集团)有限公司",
        "to": "玉溪研和工业园区",
        "vehicle": "K12346",
        "driver": "李伟",
        "typeTag": "开始任务",
        "fare": 700,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200020001"
      },
      {
        "seq": 2,
        "route": "玉溪研和工业园区 → 玉溪化肥厂",
        "goods": "中转",
        "from": "玉溪研和工业园区",
        "to": "玉溪化肥厂",
        "vehicle": "K12346",
        "driver": "李伟",
        "typeTag": "中间任务",
        "fare": 800,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200020002"
      },
      {
        "seq": 3,
        "route": "玉溪化肥厂 → 化念铁精粉卸货地",
        "goods": "铁精粉",
        "from": "玉溪化肥厂",
        "to": "化念铁精粉卸货地",
        "vehicle": "K12346",
        "driver": "李伟",
        "typeTag": "结束任务",
        "fare": 900,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200020003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0003",
    "vehicle": "K12345",
    "driver": "张建国",
    "status": "p",
    "endType": "",
    "startPool": "研和化肥厂",
    "startActual": "研和化肥厂",
    "endPool": "玉昆卸货点",
    "endActual": "玉昆卸货点",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-15 13:20",
    "endTime": "—",
    "totalDuration": "—",
    "totalDurationH": "—",
    "mileage": "85.2",
    "createTime": "—",
    "lastCalcTime": "—",
    "timeAnalysis": {
      "loading": {
        "h": null,
        "pct": 0
      },
      "driving": {
        "h": null,
        "pct": 0
      },
      "unloading": {
        "h": null,
        "pct": 0
      },
      "charging": {
        "h": null,
        "pct": 0
      },
      "total": null
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "研和化肥厂",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "研和化肥厂 → 景洪橄榄坝水泥卸货点",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "景洪橄榄坝水泥卸货点 → 景洪神石山（水泥卸货）",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "景洪神石山（水泥卸货） → 玉昆卸货点",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "研和化肥厂 → 景洪橄榄坝水泥卸货点",
        "goods": "化肥",
        "from": "研和化肥厂",
        "to": "景洪橄榄坝水泥卸货点",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "开始任务",
        "fare": 1200,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200030001"
      },
      {
        "seq": 2,
        "route": "景洪橄榄坝水泥卸货点 → 景洪神石山（水泥卸货）",
        "goods": "中转",
        "from": "景洪橄榄坝水泥卸货点",
        "to": "景洪神石山（水泥卸货）",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "中间任务",
        "fare": 1350,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200030002"
      },
      {
        "seq": 3,
        "route": "景洪神石山（水泥卸货） → 玉昆卸货点",
        "goods": "水泥",
        "from": "景洪神石山（水泥卸货）",
        "to": "玉昆卸货点",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "结束任务",
        "fare": 1500,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200030003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0004",
    "vehicle": "K08765",
    "driver": "王强",
    "status": "s",
    "endType": "自动结束",
    "startPool": "大开门水渣装货地",
    "startActual": "大开门水渣装货地",
    "endPool": "玉昆卸货点",
    "endActual": "玉昆卸货点",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-15 08:00",
    "endTime": "2026-07-18 14:30",
    "totalDuration": "3d 6h30m",
    "totalDurationH": "3d 6h30m",
    "mileage": "156.8",
    "createTime": "2026-07-18 14:30:03",
    "lastCalcTime": "2026-07-18 14:30:03",
    "timeAnalysis": {
      "loading": {
        "h": 1,
        "pct": 14.3
      },
      "driving": {
        "h": 4.8,
        "pct": 68.6
      },
      "unloading": {
        "h": 0.8,
        "pct": 11.4
      },
      "charging": {
        "h": 0.4,
        "pct": 5.7
      },
      "total": 7
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "大开门水渣装货地",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "大开门水渣装货地 → 尖峰水泥场（装货地）",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "尖峰水泥场（装货地） → 尖峰水泥厂（卸货地）",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "尖峰水泥厂（卸货地） → 玉昆卸货点",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "大开门水渣装货地 → 尖峰水泥场（装货地）",
        "goods": "水渣",
        "from": "大开门水渣装货地",
        "to": "尖峰水泥场（装货地）",
        "vehicle": "K08765",
        "driver": "王强",
        "typeTag": "开始任务",
        "fare": 500,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200040001"
      },
      {
        "seq": 2,
        "route": "尖峰水泥场（装货地） → 尖峰水泥厂（卸货地）",
        "goods": "中转",
        "from": "尖峰水泥场（装货地）",
        "to": "尖峰水泥厂（卸货地）",
        "vehicle": "K08765",
        "driver": "王强",
        "typeTag": "中间任务",
        "fare": 550,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200040002"
      },
      {
        "seq": 3,
        "route": "尖峰水泥厂（卸货地） → 玉昆卸货点",
        "goods": "水泥",
        "from": "尖峰水泥厂（卸货地）",
        "to": "玉昆卸货点",
        "vehicle": "K08765",
        "driver": "王强",
        "typeTag": "结束任务",
        "fare": 600,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200040003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0005",
    "vehicle": "K08766",
    "driver": "赵明",
    "status": "w",
    "endType": "手动结束",
    "startPool": "安宁昆钢",
    "startActual": "安宁昆钢",
    "endPool": "化念铁精粉卸货地",
    "endActual": "化念铁精粉卸货地",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-15 09:30",
    "endTime": "2026-07-17 20:15",
    "totalDuration": "3d 14h15m",
    "totalDurationH": "3d 14h15m",
    "mileage": "342.1",
    "createTime": "2026-07-17 20:15:03",
    "lastCalcTime": "2026-07-17 20:15:03",
    "timeAnalysis": {
      "loading": {
        "h": 3.5,
        "pct": 27.3
      },
      "driving": {
        "h": 5.3,
        "pct": 41.4
      },
      "unloading": {
        "h": 3,
        "pct": 23.4
      },
      "charging": {
        "h": 1,
        "pct": 7.8
      },
      "total": 12.8
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "安宁昆钢",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "安宁昆钢 → 景东钢筋下货点",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "景东钢筋下货点 → 普洱墨江通关（钢筋卸货地）",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "普洱墨江通关（钢筋卸货地） → 化念铁精粉卸货地",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "安宁昆钢 → 景东钢筋下货点",
        "goods": "钢材",
        "from": "安宁昆钢",
        "to": "景东钢筋下货点",
        "vehicle": "K08766",
        "driver": "赵明",
        "typeTag": "开始任务",
        "fare": 1400,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200050001"
      },
      {
        "seq": 2,
        "route": "景东钢筋下货点 → 普洱墨江通关（钢筋卸货地）",
        "goods": "中转",
        "from": "景东钢筋下货点",
        "to": "普洱墨江通关（钢筋卸货地）",
        "vehicle": "K08766",
        "driver": "赵明",
        "typeTag": "中间任务",
        "fare": 1350,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200050002"
      },
      {
        "seq": 3,
        "route": "普洱墨江通关（钢筋卸货地） → 化念铁精粉卸货地",
        "goods": "铁精粉",
        "from": "普洱墨江通关（钢筋卸货地）",
        "to": "化念铁精粉卸货地",
        "vehicle": "K08766",
        "driver": "赵明",
        "typeTag": "结束任务",
        "fare": 1300,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200050003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0006",
    "vehicle": "K08765",
    "driver": "李伟",
    "status": "s",
    "endType": "自动结束",
    "startPool": "玉溪水电志达混凝土有限公司",
    "startActual": "玉溪水电志达混凝土有限公司",
    "endPool": "元江干坝片区（锰矿卸货点）",
    "endActual": "元江干坝片区（锰矿卸货点）",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-15 14:00",
    "endTime": "2026-07-16 02:30",
    "totalDuration": "3d 12h30m",
    "totalDurationH": "3d 12h30m",
    "mileage": "312.5",
    "createTime": "2026-07-16 02:30:03",
    "lastCalcTime": "2026-07-16 02:30:03",
    "timeAnalysis": {
      "loading": {
        "h": 2.5,
        "pct": 24
      },
      "driving": {
        "h": 4.9,
        "pct": 47.1
      },
      "unloading": {
        "h": 2.3,
        "pct": 22.1
      },
      "charging": {
        "h": 0.7,
        "pct": 6.7
      },
      "total": 10.4
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "玉溪水电志达混凝土有限公司",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "玉溪水电志达混凝土有限公司 → 普洱景谷红狮水泥有限公司",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "普洱景谷红狮水泥有限公司 → 普洱景谷县城",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "普洱景谷县城 → 元江干坝片区（锰矿卸货点）",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "玉溪水电志达混凝土有限公司 → 普洱景谷红狮水泥有限公司",
        "goods": "水泥",
        "from": "玉溪水电志达混凝土有限公司",
        "to": "普洱景谷红狮水泥有限公司",
        "vehicle": "K08765",
        "driver": "李伟",
        "typeTag": "开始任务",
        "fare": 600,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200060001"
      },
      {
        "seq": 2,
        "route": "普洱景谷红狮水泥有限公司 → 普洱景谷县城",
        "goods": "中转",
        "from": "普洱景谷红狮水泥有限公司",
        "to": "普洱景谷县城",
        "vehicle": "K08765",
        "driver": "李伟",
        "typeTag": "中间任务",
        "fare": 700,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200060002"
      },
      {
        "seq": 3,
        "route": "普洱景谷县城 → 元江干坝片区（锰矿卸货点）",
        "goods": "锰矿",
        "from": "普洱景谷县城",
        "to": "元江干坝片区（锰矿卸货点）",
        "vehicle": "K08765",
        "driver": "李伟",
        "typeTag": "结束任务",
        "fare": 800,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200060003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0007",
    "vehicle": "K12345",
    "driver": "张建国",
    "status": "p",
    "endType": "",
    "startPool": "安宁昆钢",
    "startActual": "安宁昆钢",
    "endPool": "易门白土卸货地",
    "endActual": "易门白土卸货地",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-16 06:30",
    "endTime": "—",
    "totalDuration": "—",
    "totalDurationH": "—",
    "mileage": "145.6",
    "createTime": "—",
    "lastCalcTime": "—",
    "timeAnalysis": {
      "loading": {
        "h": null,
        "pct": 0
      },
      "driving": {
        "h": null,
        "pct": 0
      },
      "unloading": {
        "h": null,
        "pct": 0
      },
      "charging": {
        "h": null,
        "pct": 0
      },
      "total": null
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "安宁昆钢",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "安宁昆钢 → 普洱建峰水泥厂装货点",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "普洱建峰水泥厂装货点 → 普洱南屏镇化肥卸货点",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "普洱南屏镇化肥卸货点 → 易门白土卸货地",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "安宁昆钢 → 普洱建峰水泥厂装货点",
        "goods": "—",
        "from": "安宁昆钢",
        "to": "普洱建峰水泥厂装货点",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "开始任务",
        "fare": 800,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200070001"
      },
      {
        "seq": 2,
        "route": "普洱建峰水泥厂装货点 → 普洱南屏镇化肥卸货点",
        "goods": "中转",
        "from": "普洱建峰水泥厂装货点",
        "to": "普洱南屏镇化肥卸货点",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "中间任务",
        "fare": 1250,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200070002"
      },
      {
        "seq": 3,
        "route": "普洱南屏镇化肥卸货点 → 易门白土卸货地",
        "goods": "水泥",
        "from": "普洱南屏镇化肥卸货点",
        "to": "易门白土卸货地",
        "vehicle": "K12345",
        "driver": "张建国",
        "typeTag": "结束任务",
        "fare": 1700,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200070003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0008",
    "vehicle": "K12346",
    "driver": "赵明",
    "status": "qp",
    "endType": "自动结束",
    "startPool": "玉溪仙福钢铁(集团)有限公司",
    "startActual": "玉溪仙福钢铁(集团)有限公司",
    "endPool": "峨山贵州佳俊矿业",
    "endActual": "峨山贵州佳俊矿业",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-15 14:30",
    "endTime": "2026-07-14 17:50",
    "totalDuration": "3d 10h20m",
    "totalDurationH": "3d 10h20m",
    "mileage": "268.4",
    "createTime": "2026-07-14 17:50:03",
    "lastCalcTime": "2026-07-14 17:50:03",
    "timeAnalysis": {
      "loading": {
        "h": 2.8,
        "pct": 29.8
      },
      "driving": {
        "h": 4.2,
        "pct": 44.7
      },
      "unloading": {
        "h": 1.8,
        "pct": 19.1
      },
      "charging": {
        "h": 0.6,
        "pct": 6.4
      },
      "total": 9.4
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "玉溪仙福钢铁(集团)有限公司",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "玉溪仙福钢铁(集团)有限公司 → 景洪红砖卸货点",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "景洪红砖卸货点 → 西双版纳鑫禾商贸（小红砖卸货点）",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "西双版纳鑫禾商贸（小红砖卸货点） → 峨山贵州佳俊矿业",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "玉溪仙福钢铁(集团)有限公司 → 景洪红砖卸货点",
        "goods": "钢材",
        "from": "玉溪仙福钢铁(集团)有限公司",
        "to": "景洪红砖卸货点",
        "vehicle": "K12346",
        "driver": "赵明",
        "typeTag": "开始任务",
        "fare": 750,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200080001"
      },
      {
        "seq": 2,
        "route": "景洪红砖卸货点 → 西双版纳鑫禾商贸（小红砖卸货点）",
        "goods": "中转",
        "from": "景洪红砖卸货点",
        "to": "西双版纳鑫禾商贸（小红砖卸货点）",
        "vehicle": "K12346",
        "driver": "赵明",
        "typeTag": "中间任务",
        "fare": 825,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200080002"
      },
      {
        "seq": 3,
        "route": "西双版纳鑫禾商贸（小红砖卸货点） → 峨山贵州佳俊矿业",
        "goods": "矿石",
        "from": "西双版纳鑫禾商贸（小红砖卸货点）",
        "to": "峨山贵州佳俊矿业",
        "vehicle": "K12346",
        "driver": "赵明",
        "typeTag": "结束任务",
        "fare": 900,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200080003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0009",
    "vehicle": "K08766",
    "driver": "王强",
    "status": "s",
    "endType": "自动结束",
    "startPool": "研和化肥厂",
    "startActual": "研和化肥厂",
    "endPool": "杨武铁精粉下货点",
    "endActual": "杨武铁精粉下货点",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-15 15:00",
    "endTime": "2026-07-13 22:40",
    "totalDuration": "3d 13h25m",
    "totalDurationH": "3d 13h25m",
    "mileage": "298.7",
    "createTime": "2026-07-13 22:40:03",
    "lastCalcTime": "2026-07-13 22:40:03",
    "timeAnalysis": {
      "loading": {
        "h": 3.3,
        "pct": 28
      },
      "driving": {
        "h": 5.3,
        "pct": 44.9
      },
      "unloading": {
        "h": 2.3,
        "pct": 19.5
      },
      "charging": {
        "h": 0.9,
        "pct": 7.6
      },
      "total": 11.8
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "研和化肥厂",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "研和化肥厂 → 景洪关坪吉利砖厂（水泥卸货点）",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "景洪关坪吉利砖厂（水泥卸货点） → 景洪东风镇（水泥卸货地）",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "景洪东风镇（水泥卸货地） → 杨武铁精粉下货点",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "研和化肥厂 → 景洪关坪吉利砖厂（水泥卸货点）",
        "goods": "化肥",
        "from": "研和化肥厂",
        "to": "景洪关坪吉利砖厂（水泥卸货点）",
        "vehicle": "K08766",
        "driver": "王强",
        "typeTag": "开始任务",
        "fare": 1200,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200090001"
      },
      {
        "seq": 2,
        "route": "景洪关坪吉利砖厂（水泥卸货点） → 景洪东风镇（水泥卸货地）",
        "goods": "中转",
        "from": "景洪关坪吉利砖厂（水泥卸货点）",
        "to": "景洪东风镇（水泥卸货地）",
        "vehicle": "K08766",
        "driver": "王强",
        "typeTag": "中间任务",
        "fare": 1275,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200090002"
      },
      {
        "seq": 3,
        "route": "景洪东风镇（水泥卸货地） → 杨武铁精粉下货点",
        "goods": "铁精粉",
        "from": "景洪东风镇（水泥卸货地）",
        "to": "杨武铁精粉下货点",
        "vehicle": "K08766",
        "driver": "王强",
        "typeTag": "结束任务",
        "fare": 1350,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200090003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0010",
    "vehicle": "K08765",
    "driver": "赵明",
    "status": "p",
    "endType": "",
    "startPool": "大开门水渣装货地",
    "startActual": "大开门水渣装货地",
    "endPool": "峨山鑫钰公司货场",
    "endActual": "峨山鑫钰公司货场",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-16 07:00",
    "endTime": "2026-07-10 15:20",
    "totalDuration": "3d 9h50m",
    "totalDurationH": "3d 9h50m",
    "mileage": "225.3",
    "createTime": "2026-07-10 15:20:03",
    "lastCalcTime": "2026-07-10 15:20:03",
    "timeAnalysis": {
      "loading": {
        "h": null,
        "pct": 0
      },
      "driving": {
        "h": null,
        "pct": 0
      },
      "unloading": {
        "h": null,
        "pct": 0
      },
      "charging": {
        "h": null,
        "pct": 0
      },
      "total": null
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "大开门水渣装货地",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "大开门水渣装货地 → 磨憨红砖厂装货点",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "磨憨红砖厂装货点 → 版纳磨憨镇",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "版纳磨憨镇 → 峨山鑫钰公司货场",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "大开门水渣装货地 → 磨憨红砖厂装货点",
        "goods": "—",
        "from": "大开门水渣装货地",
        "to": "磨憨红砖厂装货点",
        "vehicle": "K08765",
        "driver": "赵明",
        "typeTag": "开始任务",
        "fare": 700,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200100001"
      },
      {
        "seq": 2,
        "route": "磨憨红砖厂装货点 → 版纳磨憨镇",
        "goods": "中转",
        "from": "磨憨红砖厂装货点",
        "to": "版纳磨憨镇",
        "vehicle": "K08765",
        "driver": "赵明",
        "typeTag": "中间任务",
        "fare": 1150,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200100002"
      },
      {
        "seq": 3,
        "route": "版纳磨憨镇 → 峨山鑫钰公司货场",
        "goods": "红砖",
        "from": "版纳磨憨镇",
        "to": "峨山鑫钰公司货场",
        "vehicle": "K08765",
        "driver": "赵明",
        "typeTag": "结束任务",
        "fare": 1600,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200100003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0011",
    "vehicle": "K67890",
    "driver": "李伟",
    "status": "p",
    "endType": "",
    "startPool": "玉溪仙福钢铁(集团)有限公司",
    "startActual": "玉溪仙福钢铁(集团)有限公司",
    "endPool": "化念铁精粉卸货地",
    "endActual": "化念铁精粉卸货地",
    "taskCount": "2 条任务单",
    "startTime": "2026-07-17 08:15",
    "endTime": "—",
    "totalDuration": "—",
    "totalDurationH": "—",
    "mileage": "168.4",
    "createTime": "2026-07-17 08:15:03",
    "lastCalcTime": "2026-07-30 10:05:21",
    "timeAnalysis": {
      "loading": {
        "h": 1.2,
        "pct": 21
      },
      "driving": {
        "h": 3.1,
        "pct": 54
      },
      "unloading": {
        "h": 0.9,
        "pct": 16
      },
      "charging": {
        "h": 0.5,
        "pct": 9
      },
      "total": 5.7
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "玉溪仙福钢铁(集团)有限公司",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "玉溪仙福钢铁(集团)有限公司 → 化念铁精粉卸货地",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "化念铁精粉卸货地 → 玉溪研和化肥厂",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "玉溪仙福钢铁(集团)有限公司 → 化念铁精粉卸货地",
        "goods": "铁精粉",
        "from": "玉溪仙福钢铁(集团)有限公司",
        "to": "化念铁精粉卸货地",
        "vehicle": "K67890",
        "driver": "李伟",
        "typeTag": "开始任务",
        "fare": 1500,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200110001"
      },
      {
        "seq": 2,
        "route": "化念铁精粉卸货地 → 玉溪研和化肥厂",
        "goods": "化肥",
        "from": "化念铁精粉卸货地",
        "to": "玉溪研和化肥厂",
        "vehicle": "K67890",
        "driver": "李伟",
        "typeTag": "中间任务",
        "fare": 800,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200110002"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  },
  {
    "code": "QXC-20260720-0012",
    "vehicle": "K90123",
    "driver": "王强",
    "status": "p",
    "endType": "",
    "startPool": "大开门水渣装货地",
    "startActual": "大开门水渣装货地",
    "endPool": "玉昆卸货点",
    "endActual": "玉昆卸货点",
    "taskCount": "3 条任务单",
    "startTime": "2026-07-17 09:40",
    "endTime": "—",
    "totalDuration": "—",
    "totalDurationH": "—",
    "mileage": "254.1",
    "createTime": "2026-07-17 09:40:03",
    "lastCalcTime": "2026-07-30 10:08:44",
    "timeAnalysis": {
      "loading": {
        "h": 2,
        "pct": 25
      },
      "driving": {
        "h": 4.2,
        "pct": 53
      },
      "unloading": {
        "h": 1.5,
        "pct": 19
      },
      "charging": {
        "h": 0.6,
        "pct": 8
      },
      "total": 8.3
    },
    "timeline": [
      {
        "tag": "开始任务",
        "loc": "大开门水渣装货地",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "大开门水渣装货地 → 玉昆卸货点",
        "time": "—"
      },
      {
        "tag": "中间任务",
        "loc": "玉昆卸货点 → 玉溪研和化肥厂",
        "time": "—"
      },
      {
        "tag": "结束任务",
        "loc": "玉溪研和化肥厂 → 大开门水渣装货地",
        "time": "—"
      }
    ],
    "tasks": [
      {
        "seq": 1,
        "route": "大开门水渣装货地 → 玉昆卸货点",
        "goods": "水渣",
        "from": "大开门水渣装货地",
        "to": "玉昆卸货点",
        "vehicle": "K90123",
        "driver": "王强",
        "typeTag": "开始任务",
        "fare": 1800,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200120001"
      },
      {
        "seq": 2,
        "route": "玉昆卸货点 → 玉溪研和化肥厂",
        "goods": "化肥",
        "from": "玉昆卸货点",
        "to": "玉溪研和化肥厂",
        "vehicle": "K90123",
        "driver": "王强",
        "typeTag": "中间任务",
        "fare": 900,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200120002"
      },
      {
        "seq": 3,
        "route": "玉溪研和化肥厂 → 大开门水渣装货地",
        "goods": "水渣",
        "from": "玉溪研和化肥厂",
        "to": "大开门水渣装货地",
        "vehicle": "K90123",
        "driver": "王强",
        "typeTag": "结束任务",
        "fare": 1200,
        "loadArr": "—",
        "loadLeave": "—",
        "unloadArr": "—",
        "unloadLeave": "—",
        "complete": "—",
        "loadEff": "—",
        "unloadEff": "—",
        "chargeEff": "—",
        "driveEff": "—",
        "taskId": "Y2026072200120003"
      }
    ],
    "alertStatus": "normal",
    "alertMsg": "时效数据状态：正常。四类时效时间区间无重叠，数据完整。"
  }
];

module.exports = { fences, trips, circleRows };
